ALTER TABLE properties
ADD COLUMN IF NOT EXISTS deposit BIGINT,
ADD COLUMN IF NOT EXISTS floor INT,
ADD COLUMN IF NOT EXISTS total_floors INT,
ADD COLUMN IF NOT EXISTS age_years INT,
ADD COLUMN IF NOT EXISTS facing TEXT,
ADD COLUMN IF NOT EXISTS parking BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS parking_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_url TEXT,
ADD COLUMN IF NOT EXISTS broker_contact_allowed BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS user_type TEXT DEFAULT 'user';
