ALTER TABLE property_reports ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE moderation_reports ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE moderation_reports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE news_reports ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE news_reports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE news_reports ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'open';
