ALTER TABLE properties
ADD COLUMN IF NOT EXISTS bathroom_type TEXT,
ADD COLUMN IF NOT EXISTS lease_years INT,
ADD COLUMN IF NOT EXISTS gender_preference TEXT,
ADD COLUMN IF NOT EXISTS roommates INT,
ADD COLUMN IF NOT EXISTS area TEXT;
